name: 'Create New Branch'
description: 'This action creates a new branch based on a pull request'
author: 'Your Name'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  branch_prefix:
    description: 'Prefix for the new branch name'
    required: true
  branch_suffix:
    description: 'Suffix for the new branch name'
    required: false
  base_branch:
    description: 'Name of the base branch'
    required: true

outputs:
  branch_name:
    description: 'The name of the created branch'

runs:
  using: 'node20'
  main: 'dist/index.js'