name: 'Create New Branch'
description: 'This action creates a new branch in the repository'
author: 'RH'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  branch_name:
    description: 'Name of the new branch to create'
    required: true
  base_branch:
    description: 'Name of the base branch'
    required: true
    default: 'main'

outputs:
  branch_name:
    description: 'The name of the created branch'

runs:
  using: 'node20'
  main: 'dist/index.js'